name: smart_bank
description: Smart AI-Powered Banking App (Flutter + Firebase + AI)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.6
  cloud_firestore: ^4.17.5
  firebase_messaging: ^14.9.4
  cloud_functions: ^4.7.4
  intl: ^0.19.0
  http: ^1.2.2


dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true